<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SignUp</title>
</head>
<body>
<h1 >Sign In Page</h1>
<h2>Please Enter your data:</h2>
<form action="/signIn" method="post">
    <label for="email">Enter email:</label>
    <input type="email" id="email" name="email" placeholder="Your email">
    <br>
    <label for="password">Enter password:</label>
    <input type="password" id="password" name="password" placeholder="Your password">
    <input type="submit" value="Sign In">
</form>
</body>
</html>
